### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by colormyapp** [kyleminshall/Jump#2]
Hi there,

I noticed in the game, a lag coming from the circle, sometimes, it's like something it's dragging the circle down, seeing multiple times.

Here's a video: http://quick.as/zpxofwv0

**Comment by Kilenaitor** [comment]
Due to drawing of the node with SKShapeNode. Will be resolved in update with the use of SKTextureNode instead.

**Comment by colormyapp** [comment]
Great to hear that,

When is that update coming? :)

-- 
Color My App
Sent with Airmail

On 13 Mar 2015 at 01:53:25, Kyle Minshall (notifications@github.com) wrote:

Closed #2.
